### ISSUE TITLE
PSGui vs ShowUI?

### ISSUE THREAD

**Issue by Jaykul** [ddneves/PSGUI#1]
Have you seen [ShowUI](https://github.com/show-ui/ShowUI)?

**Comment by ddneves** [comment]
Jep - sure. ShowUi is very nice for easy and simple UIs. 

But PSGUIs intention was to handle big sourcecode (therefore separating XAML / CodeBehind / other Functions) and using complex XAML structures with bindings and also using styles and more. (may be applying Corporate Identity Styles with the WPF Style) Till now it´s also somewhat experimental / prove of concept - I am still searching what else more could be possible to integrate in this Powershell module.

Also - to be honest - structures like this 

https://showui.codeplex.com/wikipage?title=Show-CPU&referringTitle=Documentation

get too fast too hard to write. But XAML can be easily managed via Visual Studio (e.g.)

Greetings

**Comment by Jaykul** [comment]
ShowUI can load XAML from Visual Studio without issues, but I'd love to improve that functionality even more ;-)

https://github.com/show-ui/ShowUI/blob/dev/Examples/VisualStudioDesigner.ps1

**Comment by ddneves** [comment]
Hi,
ah ok - i will take a look at it. Thanks for the hint :)

**Comment by ddneves** [comment]
I took a look at it - quite not bad, but you have to add all your events in the loading statement. Take a look at my actual version. It´s quite more comfortable - at least for complex GUIs. :)
